#!/bin/bash
help_text="
NAME
  blog - Creates a new Blog article

USAGE
  blog <title: spaces allowed>

DESCRIPTION
  A basic script to create a new blog article.

AUTHOR
  mjnurse.github.io - 2021
"

help_line="Creates a Blog article: blog <title: spaces allowed>"
web_desc_line="Creates a Blog article"

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
   echo "$help_text"
   exit
fi

params=$*
date_str=$(date +'%y-%m-%d')

filename=${date_str}_-_${params// /_}.md
file="$MJNWINROOT/MJN/github/mjnurse-github-io/Blog-B/$filename"
echo $filename

if [[ -f "$file" ]]; then
  read -p "File already exists - open now [yN]: " yn
  if [ "${yn^}" == "Y" ]; then
    gvim "$file"
  fi
  exit
fi

read -p "Create [yN]: " yn

if [ "${yn^}" == "Y" ]; then
   echo "---" > "$file"
   echo "title: ${date_str} - ${params}" >> "$file"
   echo "---" >> "$file"
   gvim "$file"
fi
