#!/bin/bash

if [[ "$1" == "-d" || "$1" == "--daily" ]]; then
    today=$(date +"%Y-%m-%d")
    last_day="$(cat /home/martin/.local/state/website-last_build_date.txt)"
    if [ "$today" == "$last_day" ]; then
        echo "Website already built today ($today). Skipping build."
        exit 0
    fi
    echo "$today" > /home/martin/.local/state/website-last_build_date.txt
fi

cd /home/martin/mjnurse/website-builder

for f in gen*.py; do
    echo "Running $f"
    python "$f"
done

sck -m > ../mjnurse-website/other/Shortcut_Keys.md
n -m > ../mjnurse-website/notes/Miscellaneous_Notes.md

echo "Building site"
python build-website.py --src ../mjnurse-website --out ../mjnurse.github.io

cd /home/martin/mjnurse/website-builder
push-website $1
