#!/bin/bash

cd /home/martin/mjnurse/website-builder

for f in gen*.py; do
    echo "Running $f"
    python "$f"
done

sck -m > ../mjnurse-website/other/Shortcut_Keys.md
n -m > ../mjnurse-website/notes/Miscellaneous_Notes.md

echo "Building site"
python build.py --src ../mjnurse-website --out ../mjnurse.github.io

cd /home/martin/mjnurse/website-builder
push-website
