#!/bin/bash

if [[ "$1" == "-f" ]]; then
    FORCE_PUSH=true
else
    FORCE_PUSH=false
fi

echo ---------------
echo website-builder
echo ---------------
if [[ -n "$(git status --porcelain)" ]]; then
    git status
    if $FORCE_PUSH; then
        choice="Y"
    else
        read -p "Push website-builder changes to GitHub? [yN] " choice
    fi
    if [[ "${choice^}" == "Y" ]]; then
        git add .
        if ! $FORCE_PUSH; then
            read -p "Enter commit message (blank defaults to 'various'): " commit_message
        fi
        if [[ -z "$commit_message" ]]; then
            commit_message="various"
        fi
        git commit -m "$commit_message"
        git push origin main
        echo "Changes pushed to GitHub."
    fi
else
    echo "No changes to push."
fi

cd ../mjnurse-website || exit

echo
echo ---------------
echo mjnurse-website
echo ---------------
if [[ -n "$(git status --porcelain)" ]]; then
    git status
    if $FORCE_PUSH; then
        choice="Y"
    else
        read -p "Push mjnurse-website changes to GitHub? [yN] " choice
    fi
    if [[ "${choice^}" == "Y" ]]; then
        git add .
        if ! $FORCE_PUSH; then
            read -p "Enter commit message (blank defaults to 'various'): " commit_message
        fi
        if [[ -z "$commit_message" ]]; then
            commit_message="various"
        fi
        git commit -m "$commit_message"
        git push origin main
        echo "Changes pushed to GitHub."
    fi
else
    echo "No changes to push."
fi

cd ../mjnurse.github.io || exit

echo
echo -----------------
echo mjnurse.github.io
echo -----------------
if [[ -n "$(git status --porcelain)" ]]; then
    git status
    if $FORCE_PUSH; then
        choice="Y"
    else
        read -p "Push mjnurse.github.io changes to GitHub? [yN] " choice
    fi
    if [[ "${choice^}" == "Y" ]]; then
        git add .
        if ! $FORCE_PUSH; then
            read -p "Enter commit message (blank defaults to 'various'): " commit_message
        fi
        if [[ -z "$commit_message" ]]; then
            commit_message="various"
        fi
        git commit -m "$commit_message"
        git push origin main
        echo "Changes pushed to GitHub."
    fi
else
    echo "No changes to push."
fi
