#!/bin/bash
help_text="
NAME
   ai - One line description.

USAGE
   ai [options] <image file name>

OPTIONS
   -x
      Description...

   -h|--help
      Show help text.

DESCRIPTION
   Description description description description.

AUTHOR
  mjnurse.dev - 2020
"
help_line="tbc"
desc_line="tbc"

try="Try ${0##*/} -h for more information"
tmp="${help_text##*USAGE}"
usage=$(echo "Usage: ${tmp%%OPTIONS*}" | tr -d "\n" | sed "s/  */ /g")

if [[ "$1" == "" ]]; then
  echo "${usage}"
  echo "${try}"
  exit 1
fi

if [[ "$1" == "--help" || "$1" == "-h" || "$1" == "?" ]]; then
   echo "$help_text"
   exit
fi

tmp="/tmp/ai.tmp"

find . -type d -print | grep images | sort > $tmp

echo "Select destination section for image"
echo
((section_num = 1))
echo SECTIONS:
while read -r line; do
   echo "$section_num: $line"
   (( section_num=section_num + 1 ))
done < /tmp/ai.tmp
read -rp "Select section: " chosen_num

if [[ "$chosen_num" == "" ]]; then
  exit
fi

((section_num = 1))
while read -r line; do
   if [[ "$section_num" == "$chosen_num" ]]; then
      section_dir="$line"
   fi
   (( section_num = section_num + 1 ))
done < /tmp/ai.tmp

echo
echo "Copying image: $1 to section $section_dir"

cp $1 $section_dir

echo "![](images/${1##*/})"
