#!/bin/bash
help_text="
NAME
  gen_ora_web_pgs - Creates web pages for Oracle scripts

USAGE
  gen_ora_web_pgs

DESCRIPTION
  Creates web pages for Oracle scripts.

AUTHOR
  mjnurse.dev - 2020
"
help_line="Creates web pages for Oracle scripts"

gh_home="$MJNWINROOT/MJN/github"

rm -f "$gh_home"/mjnurse-github-io/Other-O/Oracle/Script*

cd "$gh_home"/oracle

for f in $(grep -l "^-- web_desc_line" *.sql); do

   dl="$(grep '^-- web_desc_line' $f | sed 's/-- web_desc_line: *//; s/ *$//')"
   dest=$(echo "$gh_home/mjnurse-github-io/Other-O/Oracle/Script $f - $dl.md" | sed "s/ /_/g")

   echo "---" > $dest
   echo "title: $f - $dl" >> $dest
   echo "---" >> $dest
   echo "" >> $dest
   echo "\`\`\`sql" >> $dest
   cat $f >> $dest
   echo "\`\`\`" >> $dest

   echo $dest

   fdr="$(date -r $f)"
   touch -d "$fdr" $dest
done

