#!/bin/bash
help_text="
NAME
  xxxx

USAGE
  xxxx

DESCRIPTION
  xxxx

AUTHOR
  mjnurse.dev - 2021
"
help_line="Creates webs pages for cli-builder and definition files"

gh_home="$MJNWINROOT/MJN/github"

cli_base="$gh_home/mjnurse-github-io/Other-O/Command_Line_Interface_Builder"

rm -f ${cli_base}/Definition* ${cli_base}/CLI_Builder_script*

cd "$gh_home"/cli-builder

dest="${cli_base}/CLI_Builder_script.md"
echo "---" > "$dest"
echo "title: CLI builder" >> "$dest"
echo "---" >> "$dest"
echo "" >> "$dest"
echo "This bash script generates a cli (command line interface) bash script from a" >> "$dest"
echo "definition file.  The structure of the definition file is code header below. " >> "$dest"
echo "This script also generates an alias file which contains a set of alias" >> "$dest"
echo "commands which run each command in the definition file using the associated" >> "$dest"
echo "shortcut prepended with an '@'." >> "$dest"
echo "" >> "$dest"
echo "\`\`\`bash" >> "$dest"
cat cli-builder >> "$dest"
echo "\`\`\`" >> "$dest"

fdr="$(date -r cli-builder)"
touch -d "$fdr" "$dest"

# Create the definition file pages

for f in *.def; do
  echo "Generating: $f page"
  title="$(head -1 $f | sed 's/^#  *//')"
  dest="${cli_base}/Definition_File_-_${title// /_}_-_${f// /_}.md"
  echo "---" > "$dest"
  echo "title: $f" >> "$dest"
  echo "---" >> "$dest"
  echo "" >> "$dest"
  echo "\`\`\`bash" >> "$dest"
  cat $f >> "$dest"
  echo "" >> "$dest"
  echo "\`\`\`" >> "$dest"

  fdr="$(date -r $f)"
  touch -d "$fdr" "$dest"
done

